apiVersion: 1
    
datasources:
- name: prometheus
  type: prometheus
  access: proxy
  url: http://localhost:9090
  editable: true
  
- name: graphite
  type: graphite
  access: proxy
  url: http://localhost:8080
  editable: true